/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-118471-ga50d36b5fd-20250215"
#endif /* AVUTIL_FFVERSION_H */
